% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created Wed Nov 02 10:56:57 COT 2016
%
% This script assumes these variables are defined:
%
%   irisInputs - input data.
%   irisTargets - target data.
clear all;close all;clc
load('redNeuronal.mat');
x = irisInputs;
t = irisTargets;

% Create a Pattern Recognition Network
hiddenLayerSize = 10;
net = patternnet(hiddenLayerSize);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;


% Train the Network
[net,tr] = train(net,x,t);

save('redNeuronal.mat');

